### ISSUE TITLE
Does Not Work With Laravel 5

### ISSUE THREAD

**Issue by killermedia** [Stolz/Assets#57]
I do not know if you are already working on a new version for Laravel 5 (I assume you are), but I'd just like you to know, it does not work at all with L5. I could be mistaken of course, but I doubt it. There is a serious misconfiguration. Please fix or heck hit me up and maybe I can help.

Kindest Regards,
Ben

**Comment by killermedia** [comment]
Namespace issue more than likely. L5, has finally introduced complete namepsace usage.

**Comment by killermedia** [comment]
namespace*** hah

**Comment by Stolz** [comment]
@killermedia I'm afraid saying 'does not work at all' does not help at all ;). What problem are you having? What error message?. Not only the Laravel 5 version is ready and released since a few days ago, but also right now L5 is the only Laravel version officially supported.

Take a look at issue #54 and if it does not fix your problem report back (with full details: the error message, the composer version of the package you are using, and a sample code that triggers the error) and I'll reopen this issue again.
