### ISSUE TITLE
Receiving mkdir() permission denied error when pipeline set to true

### ISSUE THREAD

**Issue by tylerjvick** [Stolz/Assets#63]
Hello,

While attempting to configure a new laravel project (migrating my L4 project to L5) I now receive the error:
```
    ErrorException in Manager.php line 457:
    mkdir(): Permission denied
```
I believe that my permissions are set correctly on my public folder, and this issue only occurs when pipeline is set to true. Additionally, I have not deployed my new project yet, and have only been using the 'php artisan serve' command to test.

I have not changed any of the directories in the config, as my assets are located within public/js and public/css, and the 'min' folder should still be created within their respective folders.

Any help on this matter would be greatly appreciated, as I really would like to use the pipeline feature!

**Comment by Stolz** [comment]
First, I'm closing this issue because if there are no permission for using `mkdir` then also there are no permissions to change the permissions that will allow the `mkdir`. Therefore there is nothing from the package point of view that can be used to fix your issue.

Second, if you are using an unix-like operative system please provide:
- Your `public_dir` config option value.
- The full (from root) directory hierarchy subtree with the permissions of **each** directory in the subtree.
- The filesystem username and userid of the user you are using to run your PHP application.

Remember in unix-like filesystems the folders' permissions cascade, so is not enough to check the final path permissions but also the upstream folders permissions.

If you are not using a unix-lixe OS, sorry but I can't help you
