### ISSUE TITLE
Concatenating .js files creates invalid JavaScript

### ISSUE THREAD

**Issue by fisharebest** [Stolz/Assets#77]
I am using 3rd party javascript libraries which are already minified, and which **DO NOT** contain a final semi-colon or new-line.

Each file is valid, but the concatenation is not.  For example, create two such files as follows:

```sh
echo -n "x='foo'" > foo.js
echo -n "y='bar'" > bar.js
```

Now, when `foo.js` and `bar.js` are pipelined, the resulting file contains `x='foo'y='bar'`.

In `gatherLinks()`, perhaps add `$buffer .= "\n";`.

**Comment by Stolz** [comment]
This is a JavaScript problem and even the solution for your case is easy I think patching the library to deal with all the possible JS problems is out of the scope. The library itself leverages all the minification to another external library.

Since I recall you are [already using](https://github.com/Stolz/Assets/issues/38#issuecomment-57718074) the [fetch_command](https://github.com/Stolz/Assets/blob/master/API.md#fetch_command)  config option, you can add the fix yourself:

	'fetch_command' => function ($asset) {
		/* ... original code ... */

		return $processed . PHP_EOL;
	},

**Comment by fisharebest** [comment]
> Also, I suggest you to contact the authors of those JS libraries and suggest them to use semicolons because, even they are not required, using them is recommended for many good reasons.

FYI, I see this problem with major libraries, including bootstrap and jquery-migrate.

**Comment by Stolz** [comment]
Fair enough. I just added the fix. I hope it works for you.

**Comment by fisharebest** [comment]
Perfect.  Thanks!
