### ISSUE TITLE
Additional issue in last version 0.1.7 on Laravel 4

### ISSUE THREAD

**Issue by maksimru** [Stolz/Assets#84]
Command "php artisan asset:flush" returns

PHP Fatal error:  Call to undefined function Stolz\Assets\Laravel\config() in /vendor/stolz/assets/src/Laravel/FlushPipelineCommand.php on line 69
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined function Stolz\\Assets\\Laravel\\config()","file":"\/vendor\/stolz\/assets\/src\/Laravel\/FlushPipelineCommand.php","line":69}}

Previous version worked fine.

**Comment by Stolz** [comment]
As [announced on December of 2014](https://github.com/Stolz/Assets/releases/tag/0.0.9) Laravel 4 is no longer supported.

If you are still using Laravel 4 you you have a few options:

- Use an old release of the library (i.e: `composer require "stolz/assets:0.0.*"`) but you won't keep up to date with the latest work.
- Use your own Laravel service provider.

A sample service provider and artisan command for Laravel 4 are provided. They both work at the time of writing this but this may change in the future since I don't plan to maintain them.

To use them, in your `config/app.php` file, use `Stolz\Assets\Laravel\LegacyServiceProvider` instead of `Stolz\Assets\Laravel\ServiceProvider`.

The sample files will eventually be deleted so make sure you make a copy of them. In that case, also make sure you address them in the `config/app.php` using the proper namespace of your copy.
